name: Publish to crates.io
on:
  push:
    tags: ['v*']  # Triggers when pushing tags starting with 'v'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo publish -p jxl_macros
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
    - run: cargo publish -p jxl_simd
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
    - run: cargo publish -p jxl_transforms
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
    - run: cargo publish -p jxl
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
